// GENERATED CODE - DO NOT EDIT

// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: specify_nonobvious_property_types, specify_nonobvious_local_variable_types

import 'dart:ui' as ui;

import 'package:flutter/material.dart';

import 'custom_text_style.dart';
import 'google_fonts_base.dart';
import 'google_fonts_parts/part_a.dart';
import 'google_fonts_parts/part_b.dart';
import 'google_fonts_parts/part_c.dart';
import 'google_fonts_parts/part_d.dart';
import 'google_fonts_parts/part_e.dart';
import 'google_fonts_parts/part_f.dart';
import 'google_fonts_parts/part_g.dart';
import 'google_fonts_parts/part_h.dart';
import 'google_fonts_parts/part_i.dart';
import 'google_fonts_parts/part_j.dart';
import 'google_fonts_parts/part_k.dart';
import 'google_fonts_parts/part_l.dart';
import 'google_fonts_parts/part_m.dart';
import 'google_fonts_parts/part_n.dart';
import 'google_fonts_parts/part_o.dart';
import 'google_fonts_parts/part_p.dart';
import 'google_fonts_parts/part_q.dart';
import 'google_fonts_parts/part_r.dart';
import 'google_fonts_parts/part_s.dart';
import 'google_fonts_parts/part_t.dart';
import 'google_fonts_parts/part_u.dart';
import 'google_fonts_parts/part_v.dart';
import 'google_fonts_parts/part_w.dart';
import 'google_fonts_parts/part_x.dart';
import 'google_fonts_parts/part_y.dart';
import 'google_fonts_parts/part_z.dart';

/// A collection of properties used to specify custom behavior of the
/// GoogleFonts library.
class Config {
  /// Whether or not the GoogleFonts library can make requests to
  /// [fonts.google.com](https://fonts.google.com/) to retrieve font files.
  bool allowRuntimeFetching = true;
}

/// Provides configuration, and static methods to obtain [TextStyle]s and [TextTheme]s.
///
/// {@youtube 560 315 https://www.youtube.com/watch?v=8Vzv2CdbEY0}
///
/// Obtain a map of available fonts with [asMap]. Retrieve a font by family name
/// with [getFont]. Retrieve a text theme by its font family name [getTextTheme].
///
/// Check out the [README](https://pub.dev/packages/google_fonts) for more info.
class GoogleFonts {
  /// Configuration for the [GoogleFonts] library.
  ///
  /// Use this to define custom behavior of the GoogleFonts library in your app.
  /// For example, if you do not want the GoogleFonts library to make any HTTP
  /// requests for fonts, add the following snippet to your app's `main` method.
  ///
  /// ```dart
  /// GoogleFonts.config.allowRuntimeFetching = false;
  /// ```
  static final Config config = Config();

  /// Returns a [Future] which resolves when requested fonts have finished
  /// loading and are ready to be rendered on screen.
  ///
  /// Usage:
  /// ```dart
  /// GoogleFonts.lato();
  /// GoogleFonts.pacificoTextTheme();
  /// await GoogleFonts.pendingFonts(); // <-- waits until Lato and Pacifico files have loaded.
  /// ```
  ///
  /// To keep things tidy, on can also pass in requested fonts as a list
  /// to [pendingFonts].
  ///
  /// ```dart
  /// await GoogleFonts.pendingFonts([
  ///   GoogleFonts.lato(),
  ///   GoogleFonts.pacificoTextTheme()
  /// ]);
  /// ```
  ///
  /// To avoid visual font swaps that occur when a font is loading,
  /// consider using [FutureBuilder]. Note: This future cannot be created in
  /// [build], as described in [FutureBuilder]'s documentation.
  ///
  /// ```dart
  /// late Future googleFontsPending;
  ///
  /// @override
  /// void initState() {
  ///   super.initState();
  ///   googleFontsPending = GoogleFonts.pendingFonts([
  ///     ...
  ///   ]);
  /// }
  ///
  /// @override
  /// Widget build(BuildContext context) {
  ///   return FutureBuilder(
  ///     future: googleFontsPending,
  ///     builder: (context, snapshot) {
  ///       if (snapshot.connectionState != ConnectionState.done) {
  ///         return const SizedBox();
  ///       }
  ///       ...
  ///     }
  ///   );
  /// }
  /// ```
  static Future<List<void>> pendingFonts([List<dynamic>? _]) => Future.wait(pendingFontFutures);

  /// Get a map of all available fonts.
  ///
  /// Returns a map where the key is the name of the font family and the value
  /// is the corresponding [GoogleFonts] method.
  static Map<
      String,
      CustomTextStyle Function({
        CustomTextStyle? textStyle,
        Color? color,
        Color? backgroundColor,
        double? fontSize,
        FontWeight? fontWeight,
        FontStyle? fontStyle,
        double? letterSpacing,
        double? wordSpacing,
        TextBaseline? textBaseline,
        double? height,
        Locale? locale,
        Paint? foreground,
        Paint? background,
        List<ui.Shadow>? shadows,
        List<ui.FontFeature>? fontFeatures,
        TextDecoration? decoration,
        Color? decorationColor,
        TextDecorationStyle? decorationStyle,
        double? decorationThickness,
      })> asMap() => const {
        'ABeeZee': PartA.aBeeZee,
        'ADLaM Display': PartA.aDLaMDisplay,
        'AR One Sans': PartA.arOneSans,
        'Abel': PartA.abel,
        'Abhaya Libre': PartA.abhayaLibre,
        'Aboreto': PartA.aboreto,
        'Abril Fatface': PartA.abrilFatface,
        'Abyssinica SIL': PartA.abyssinicaSil,
        'Aclonica': PartA.aclonica,
        'Acme': PartA.acme,
        'Actor': PartA.actor,
        'Adamina': PartA.adamina,
        'Advent Pro': PartA.adventPro,
        'Afacad': PartA.afacad,
        'Agbalumo': PartA.agbalumo,
        'Agdasima': PartA.agdasima,
        'Aguafina Script': PartA.aguafinaScript,
        'Akatab': PartA.akatab,
        'Akaya Kanadaka': PartA.akayaKanadaka,
        'Akaya Telivigala': PartA.akayaTelivigala,
        'Akronim': PartA.akronim,
        'Akshar': PartA.akshar,
        'Aladin': PartA.aladin,
        'Alata': PartA.alata,
        'Alatsi': PartA.alatsi,
        'Albert Sans': PartA.albertSans,
        'Aldrich': PartA.aldrich,
        'Alef': PartA.alef,
        'Alegreya': PartA.alegreya,
        'Alegreya SC': PartA.alegreyaSc,
        'Alegreya Sans': PartA.alegreyaSans,
        'Alegreya Sans SC': PartA.alegreyaSansSc,
        'Aleo': PartA.aleo,
        'Alex Brush': PartA.alexBrush,
        'Alexandria': PartA.alexandria,
        'Alfa Slab One': PartA.alfaSlabOne,
        'Alice': PartA.alice,
        'Alike': PartA.alike,
        'Alike Angular': PartA.alikeAngular,
        'Alkalami': PartA.alkalami,
        'Alkatra': PartA.alkatra,
        'Allan': PartA.allan,
        'Allerta': PartA.allerta,
        'Allerta Stencil': PartA.allertaStencil,
        'Allison': PartA.allison,
        'Allura': PartA.allura,
        'Almarai': PartA.almarai,
        'Almendra': PartA.almendra,
        'Almendra Display': PartA.almendraDisplay,
        'Almendra SC': PartA.almendraSc,
        'Alumni Sans': PartA.alumniSans,
        'Alumni Sans Collegiate One': PartA.alumniSansCollegiateOne,
        'Alumni Sans Inline One': PartA.alumniSansInlineOne,
        'Alumni Sans Pinstripe': PartA.alumniSansPinstripe,
        'Amarante': PartA.amarante,
        'Amaranth': PartA.amaranth,
        'Amatic SC': PartA.amaticSc,
        'Amethysta': PartA.amethysta,
        'Amiko': PartA.amiko,
        'Amiri': PartA.amiri,
        'Amiri Quran': PartA.amiriQuran,
        'Amita': PartA.amita,
        'Anaheim': PartA.anaheim,
        'Andada Pro': PartA.andadaPro,
        'Andika': PartA.andika,
        'Anek Bangla': PartA.anekBangla,
        'Anek Devanagari': PartA.anekDevanagari,
        'Anek Gujarati': PartA.anekGujarati,
        'Anek Gurmukhi': PartA.anekGurmukhi,
        'Anek Kannada': PartA.anekKannada,
        'Anek Latin': PartA.anekLatin,
        'Anek Malayalam': PartA.anekMalayalam,
        'Anek Odia': PartA.anekOdia,
        'Anek Tamil': PartA.anekTamil,
        'Anek Telugu': PartA.anekTelugu,
        'Angkor': PartA.angkor,
        'Annapurna SIL': PartA.annapurnaSil,
        'Annie Use Your Telescope': PartA.annieUseYourTelescope,
        'Anonymous Pro': PartA.anonymousPro,
        'Anta': PartA.anta,
        'Antic': PartA.antic,
        'Antic Didone': PartA.anticDidone,
        'Antic Slab': PartA.anticSlab,
        'Anton': PartA.anton,
        'Anton SC': PartA.antonSc,
        'Antonio': PartA.antonio,
        'Anuphan': PartA.anuphan,
        'Anybody': PartA.anybody,
        'Aoboshi One': PartA.aoboshiOne,
        'Arapey': PartA.arapey,
        'Arbutus': PartA.arbutus,
        'Arbutus Slab': PartA.arbutusSlab,
        'Architects Daughter': PartA.architectsDaughter,
        'Archivo': PartA.archivo,
        'Archivo Black': PartA.archivoBlack,
        'Archivo Narrow': PartA.archivoNarrow,
        'Are You Serious': PartA.areYouSerious,
        'Aref Ruqaa': PartA.arefRuqaa,
        'Aref Ruqaa Ink': PartA.arefRuqaaInk,
        'Arima': PartA.arima,
        'Arimo': PartA.arimo,
        'Arizonia': PartA.arizonia,
        'Armata': PartA.armata,
        'Arsenal': PartA.arsenal,
        'Arsenal SC': PartA.arsenalSc,
        'Artifika': PartA.artifika,
        'Arvo': PartA.arvo,
        'Arya': PartA.arya,
        'Asap': PartA.asap,
        'Asap Condensed': PartA.asapCondensed,
        'Asar': PartA.asar,
        'Asset': PartA.asset,
        'Assistant': PartA.assistant,
        'Astloch': PartA.astloch,
        'Asul': PartA.asul,
        'Athiti': PartA.athiti,
        'Atkinson Hyperlegible': PartA.atkinsonHyperlegible,
        'Atma': PartA.atma,
        'Atomic Age': PartA.atomicAge,
        'Aubrey': PartA.aubrey,
        'Audiowide': PartA.audiowide,
        'Autour One': PartA.autourOne,
        'Average': PartA.average,
        'Average Sans': PartA.averageSans,
        'Averia Gruesa Libre': PartA.averiaGruesaLibre,
        'Averia Libre': PartA.averiaLibre,
        'Averia Sans Libre': PartA.averiaSansLibre,
        'Averia Serif Libre': PartA.averiaSerifLibre,
        'Azeret Mono': PartA.azeretMono,
        'B612': PartB.b612,
        'B612 Mono': PartB.b612Mono,
        'BIZ UDGothic': PartB.bizUDGothic,
        'BIZ UDMincho': PartB.bizUDMincho,
        'BIZ UDPGothic': PartB.bizUDPGothic,
        'BIZ UDPMincho': PartB.bizUDPMincho,
        'Babylonica': PartB.babylonica,
        'Bacasime Antique': PartB.bacasimeAntique,
        'Bad Script': PartB.badScript,
        'Bagel Fat One': PartB.bagelFatOne,
        'Bahiana': PartB.bahiana,
        'Bahianita': PartB.bahianita,
        'Bai Jamjuree': PartB.baiJamjuree,
        'Bakbak One': PartB.bakbakOne,
        'Ballet': PartB.ballet,
        'Baloo 2': PartB.baloo2,
        'Baloo Bhai 2': PartB.balooBhai2,
        'Baloo Bhaijaan 2': PartB.balooBhaijaan2,
        'Baloo Bhaina 2': PartB.balooBhaina2,
        'Baloo Chettan 2': PartB.balooChettan2,
        'Baloo Da 2': PartB.balooDa2,
        'Baloo Paaji 2': PartB.balooPaaji2,
        'Baloo Tamma 2': PartB.balooTamma2,
        'Baloo Tammudu 2': PartB.balooTammudu2,
        'Baloo Thambi 2': PartB.balooThambi2,
        'Balsamiq Sans': PartB.balsamiqSans,
        'Balthazar': PartB.balthazar,
        'Bangers': PartB.bangers,
        'Barlow': PartB.barlow,
        'Barlow Condensed': PartB.barlowCondensed,
        'Barlow Semi Condensed': PartB.barlowSemiCondensed,
        'Barriecito': PartB.barriecito,
        'Barrio': PartB.barrio,
        'Basic': PartB.basic,
        'Baskervville': PartB.baskervville,
        'Baskervville SC': PartB.baskervvilleSc,
        'Battambang': PartB.battambang,
        'Baumans': PartB.baumans,
        'Bayon': PartB.bayon,
        'Be Vietnam Pro': PartB.beVietnamPro,
        'Beau Rivage': PartB.beauRivage,
        'Bebas Neue': PartB.bebasNeue,
        'Beiruti': PartB.beiruti,
        'Belanosima': PartB.belanosima,
        'Belgrano': PartB.belgrano,
        'Bellefair': PartB.bellefair,
        'Belleza': PartB.belleza,
        'Bellota': PartB.bellota,
        'Bellota Text': PartB.bellotaText,
        'BenchNine': PartB.benchNine,
        'Benne': PartB.benne,
        'Bentham': PartB.bentham,
        'Berkshire Swash': PartB.berkshireSwash,
        'Besley': PartB.besley,
        'Beth Ellen': PartB.bethEllen,
        'Bevan': PartB.bevan,
        'BhuTuka Expanded One': PartB.bhuTukaExpandedOne,
        'Big Shoulders Display': PartB.bigShouldersDisplay,
        'Big Shoulders Inline Display': PartB.bigShouldersInlineDisplay,
        'Big Shoulders Inline Text': PartB.bigShouldersInlineText,
        'Big Shoulders Stencil Display': PartB.bigShouldersStencilDisplay,
        'Big Shoulders Stencil Text': PartB.bigShouldersStencilText,
        'Big Shoulders Text': PartB.bigShouldersText,
        'Bigelow Rules': PartB.bigelowRules,
        'Bigshot One': PartB.bigshotOne,
        'Bilbo': PartB.bilbo,
        'Bilbo Swash Caps': PartB.bilboSwashCaps,
        'BioRhyme': PartB.bioRhyme,
        'BioRhyme Expanded': PartB.bioRhymeExpanded,
        'Birthstone': PartB.birthstone,
        'Birthstone Bounce': PartB.birthstoneBounce,
        'Biryani': PartB.biryani,
        'Bitter': PartB.bitter,
        'Black And White Picture': PartB.blackAndWhitePicture,
        'Black Han Sans': PartB.blackHanSans,
        'Black Ops One': PartB.blackOpsOne,
        'Blaka': PartB.blaka,
        'Blaka Hollow': PartB.blakaHollow,
        'Blaka Ink': PartB.blakaInk,
        'Blinker': PartB.blinker,
        'Bodoni Moda': PartB.bodoniModa,
        'Bodoni Moda SC': PartB.bodoniModaSc,
        'Bokor': PartB.bokor,
        'Bona Nova': PartB.bonaNova,
        'Bona Nova SC': PartB.bonaNovaSc,
        'Bonbon': PartB.bonbon,
        'Bonheur Royale': PartB.bonheurRoyale,
        'Boogaloo': PartB.boogaloo,
        'Borel': PartB.borel,
        'Bowlby One': PartB.bowlbyOne,
        'Bowlby One SC': PartB.bowlbyOneSc,
        'Braah One': PartB.braahOne,
        'Brawler': PartB.brawler,
        'Bree Serif': PartB.breeSerif,
        'Bricolage Grotesque': PartB.bricolageGrotesque,
        'Bruno Ace': PartB.brunoAce,
        'Bruno Ace SC': PartB.brunoAceSc,
        'Brygada 1918': PartB.brygada1918,
        'Bubblegum Sans': PartB.bubblegumSans,
        'Bubbler One': PartB.bubblerOne,
        'Buda': PartB.buda,
        'Buenard': PartB.buenard,
        'Bungee': PartB.bungee,
        'Bungee Hairline': PartB.bungeeHairline,
        'Bungee Inline': PartB.bungeeInline,
        'Bungee Outline': PartB.bungeeOutline,
        'Bungee Shade': PartB.bungeeShade,
        'Bungee Spice': PartB.bungeeSpice,
        'Butcherman': PartB.butcherman,
        'Butterfly Kids': PartB.butterflyKids,
        'Cabin': PartC.cabin,
        'Cabin Condensed': PartC.cabinCondensed,
        'Cabin Sketch': PartC.cabinSketch,
        'Cactus Classical Serif': PartC.cactusClassicalSerif,
        'Caesar Dressing': PartC.caesarDressing,
        'Cagliostro': PartC.cagliostro,
        'Cairo': PartC.cairo,
        'Cairo Play': PartC.cairoPlay,
        'Caladea': PartC.caladea,
        'Calistoga': PartC.calistoga,
        'Calligraffitti': PartC.calligraffitti,
        'Cambay': PartC.cambay,
        'Cambo': PartC.cambo,
        'Candal': PartC.candal,
        'Cantarell': PartC.cantarell,
        'Cantata One': PartC.cantataOne,
        'Cantora One': PartC.cantoraOne,
        'Caprasimo': PartC.caprasimo,
        'Capriola': PartC.capriola,
        'Caramel': PartC.caramel,
        'Carattere': PartC.carattere,
        'Cardo': PartC.cardo,
        'Carlito': PartC.carlito,
        'Carme': PartC.carme,
        'Carrois Gothic': PartC.carroisGothic,
        'Carrois Gothic SC': PartC.carroisGothicSc,
        'Carter One': PartC.carterOne,
        'Castoro': PartC.castoro,
        'Castoro Titling': PartC.castoroTitling,
        'Catamaran': PartC.catamaran,
        'Caudex': PartC.caudex,
        'Caveat': PartC.caveat,
        'Caveat Brush': PartC.caveatBrush,
        'Cedarville Cursive': PartC.cedarvilleCursive,
        'Ceviche One': PartC.cevicheOne,
        'Chakra Petch': PartC.chakraPetch,
        'Changa': PartC.changa,
        'Changa One': PartC.changaOne,
        'Chango': PartC.chango,
        'Charis SIL': PartC.charisSil,
        'Charm': PartC.charm,
        'Charmonman': PartC.charmonman,
        'Chathura': PartC.chathura,
        'Chau Philomene One': PartC.chauPhilomeneOne,
        'Chela One': PartC.chelaOne,
        'Chelsea Market': PartC.chelseaMarket,
        'Chenla': PartC.chenla,
        'Cherish': PartC.cherish,
        'Cherry Bomb One': PartC.cherryBombOne,
        'Cherry Cream Soda': PartC.cherryCreamSoda,
        'Cherry Swash': PartC.cherrySwash,
        'Chewy': PartC.chewy,
        'Chicle': PartC.chicle,
        'Chilanka': PartC.chilanka,
        'Chivo': PartC.chivo,
        'Chivo Mono': PartC.chivoMono,
        'Chocolate Classical Sans': PartC.chocolateClassicalSans,
        'Chokokutai': PartC.chokokutai,
        'Chonburi': PartC.chonburi,
        'Cinzel': PartC.cinzel,
        'Cinzel Decorative': PartC.cinzelDecorative,
        'Clicker Script': PartC.clickerScript,
        'Climate Crisis': PartC.climateCrisis,
        'Coda': PartC.coda,
        'Codystar': PartC.codystar,
        'Coiny': PartC.coiny,
        'Combo': PartC.combo,
        'Comfortaa': PartC.comfortaa,
        'Comforter': PartC.comforter,
        'Comforter Brush': PartC.comforterBrush,
        'Comic Neue': PartC.comicNeue,
        'Coming Soon': PartC.comingSoon,
        'Comme': PartC.comme,
        'Commissioner': PartC.commissioner,
        'Concert One': PartC.concertOne,
        'Condiment': PartC.condiment,
        'Content': PartC.content,
        'Contrail One': PartC.contrailOne,
        'Convergence': PartC.convergence,
        'Cookie': PartC.cookie,
        'Copse': PartC.copse,
        'Corben': PartC.corben,
        'Corinthia': PartC.corinthia,
        'Cormorant': PartC.cormorant,
        'Cormorant Garamond': PartC.cormorantGaramond,
        'Cormorant Infant': PartC.cormorantInfant,
        'Cormorant SC': PartC.cormorantSc,
        'Cormorant Unicase': PartC.cormorantUnicase,
        'Cormorant Upright': PartC.cormorantUpright,
        'Courgette': PartC.courgette,
        'Courier Prime': PartC.courierPrime,
        'Cousine': PartC.cousine,
        'Coustard': PartC.coustard,
        'Covered By Your Grace': PartC.coveredByYourGrace,
        'Crafty Girls': PartC.craftyGirls,
        'Creepster': PartC.creepster,
        'Crete Round': PartC.creteRound,
        'Crimson Pro': PartC.crimsonPro,
        'Crimson Text': PartC.crimsonText,
        'Croissant One': PartC.croissantOne,
        'Crushed': PartC.crushed,
        'Cuprum': PartC.cuprum,
        'Cute Font': PartC.cuteFont,
        'Cutive': PartC.cutive,
        'Cutive Mono': PartC.cutiveMono,
        'DM Mono': PartD.dmMono,
        'DM Sans': PartD.dmSans,
        'DM Serif Display': PartD.dmSerifDisplay,
        'DM Serif Text': PartD.dmSerifText,
        'Dai Banna SIL': PartD.daiBannaSil,
        'Damion': PartD.damion,
        'Dancing Script': PartD.dancingScript,
        'Danfo': PartD.danfo,
        'Dangrek': PartD.dangrek,
        'Darker Grotesque': PartD.darkerGrotesque,
        'Darumadrop One': PartD.darumadropOne,
        'David Libre': PartD.davidLibre,
        'Dawning of a New Day': PartD.dawningOfANewDay,
        'Days One': PartD.daysOne,
        'Dekko': PartD.dekko,
        'Dela Gothic One': PartD.delaGothicOne,
        'Delicious Handrawn': PartD.deliciousHandrawn,
        'Delius': PartD.delius,
        'Delius Swash Caps': PartD.deliusSwashCaps,
        'Delius Unicase': PartD.deliusUnicase,
        'Della Respira': PartD.dellaRespira,
        'Denk One': PartD.denkOne,
        'Devonshire': PartD.devonshire,
        'Dhurjati': PartD.dhurjati,
        'Didact Gothic': PartD.didactGothic,
        'Diphylleia': PartD.diphylleia,
        'Diplomata': PartD.diplomata,
        'Diplomata SC': PartD.diplomataSc,
        'Do Hyeon': PartD.doHyeon,
        'Dokdo': PartD.dokdo,
        'Domine': PartD.domine,
        'Donegal One': PartD.donegalOne,
        'Dongle': PartD.dongle,
        'Doppio One': PartD.doppioOne,
        'Dorsa': PartD.dorsa,
        'Dosis': PartD.dosis,
        'DotGothic16': PartD.dotGothic16,
        'Dr Sugiyama': PartD.drSugiyama,
        'Duru Sans': PartD.duruSans,
        'DynaPuff': PartD.dynaPuff,
        'Dynalight': PartD.dynalight,
        'EB Garamond': PartE.ebGaramond,
        'Eagle Lake': PartE.eagleLake,
        'East Sea Dokdo': PartE.eastSeaDokdo,
        'Eater': PartE.eater,
        'Economica': PartE.economica,
        'Eczar': PartE.eczar,
        'Edu AU VIC WA NT Hand': PartE.eduAuVicWaNtHand,
        'Edu NSW ACT Foundation': PartE.eduNswActFoundation,
        'Edu QLD Beginner': PartE.eduQldBeginner,
        'Edu SA Beginner': PartE.eduSaBeginner,
        'Edu TAS Beginner': PartE.eduTasBeginner,
        'Edu VIC WA NT Beginner': PartE.eduVicWaNtBeginner,
        'El Messiri': PartE.elMessiri,
        'Electrolize': PartE.electrolize,
        'Elsie': PartE.elsie,
        'Elsie Swash Caps': PartE.elsieSwashCaps,
        'Emblema One': PartE.emblemaOne,
        'Emilys Candy': PartE.emilysCandy,
        'Encode Sans': PartE.encodeSans,
        'Encode Sans Condensed': PartE.encodeSansCondensed,
        'Encode Sans Expanded': PartE.encodeSansExpanded,
        'Encode Sans SC': PartE.encodeSansSc,
        'Encode Sans Semi Condensed': PartE.encodeSansSemiCondensed,
        'Encode Sans Semi Expanded': PartE.encodeSansSemiExpanded,
        'Engagement': PartE.engagement,
        'Englebert': PartE.englebert,
        'Enriqueta': PartE.enriqueta,
        'Ephesis': PartE.ephesis,
        'Epilogue': PartE.epilogue,
        'Erica One': PartE.ericaOne,
        'Esteban': PartE.esteban,
        'Estonia': PartE.estonia,
        'Euphoria Script': PartE.euphoriaScript,
        'Ewert': PartE.ewert,
        'Exo': PartE.exo,
        'Exo 2': PartE.exo2,
        'Expletus Sans': PartE.expletusSans,
        'Explora': PartE.explora,
        'Fahkwang': PartF.fahkwang,
        'Familjen Grotesk': PartF.familjenGrotesk,
        'Fanwood Text': PartF.fanwoodText,
        'Farro': PartF.farro,
        'Farsan': PartF.farsan,
        'Fascinate': PartF.fascinate,
        'Fascinate Inline': PartF.fascinateInline,
        'Faster One': PartF.fasterOne,
        'Fasthand': PartF.fasthand,
        'Fauna One': PartF.faunaOne,
        'Faustina': PartF.faustina,
        'Federant': PartF.federant,
        'Federo': PartF.federo,
        'Felipa': PartF.felipa,
        'Fenix': PartF.fenix,
        'Festive': PartF.festive,
        'Figtree': PartF.figtree,
        'Finger Paint': PartF.fingerPaint,
        'Finlandica': PartF.finlandica,
        'Fira Code': PartF.firaCode,
        'Fira Mono': PartF.firaMono,
        'Fira Sans': PartF.firaSans,
        'Fira Sans Condensed': PartF.firaSansCondensed,
        'Fira Sans Extra Condensed': PartF.firaSansExtraCondensed,
        'Fjalla One': PartF.fjallaOne,
        'Fjord One': PartF.fjordOne,
        'Flamenco': PartF.flamenco,
        'Flavors': PartF.flavors,
        'Fleur De Leah': PartF.fleurDeLeah,
        'Flow Block': PartF.flowBlock,
        'Flow Circular': PartF.flowCircular,
        'Flow Rounded': PartF.flowRounded,
        'Foldit': PartF.foldit,
        'Fondamento': PartF.fondamento,
        'Fontdiner Swanky': PartF.fontdinerSwanky,
        'Forum': PartF.forum,
        'Fragment Mono': PartF.fragmentMono,
        'Francois One': PartF.francoisOne,
        'Frank Ruhl Libre': PartF.frankRuhlLibre,
        'Fraunces': PartF.fraunces,
        'Freckle Face': PartF.freckleFace,
        'Fredericka the Great': PartF.frederickaTheGreat,
        'Fredoka': PartF.fredoka,
        'Freehand': PartF.freehand,
        'Freeman': PartF.freeman,
        'Fresca': PartF.fresca,
        'Frijole': PartF.frijole,
        'Fruktur': PartF.fruktur,
        'Fugaz One': PartF.fugazOne,
        'Fuggles': PartF.fuggles,
        'Fustat': PartF.fustat,
        'Fuzzy Bubbles': PartF.fuzzyBubbles,
        'GFS Didot': PartG.gfsDidot,
        'GFS Neohellenic': PartG.gfsNeohellenic,
        'Ga Maamli': PartG.gaMaamli,
        'Gabarito': PartG.gabarito,
        'Gabriela': PartG.gabriela,
        'Gaegu': PartG.gaegu,
        'Gafata': PartG.gafata,
        'Gajraj One': PartG.gajrajOne,
        'Galada': PartG.galada,
        'Galdeano': PartG.galdeano,
        'Galindo': PartG.galindo,
        'Gamja Flower': PartG.gamjaFlower,
        'Gantari': PartG.gantari,
        'Gasoek One': PartG.gasoekOne,
        'Gayathri': PartG.gayathri,
        'Gelasio': PartG.gelasio,
        'Gemunu Libre': PartG.gemunuLibre,
        'Genos': PartG.genos,
        'Gentium Book Plus': PartG.gentiumBookPlus,
        'Gentium Plus': PartG.gentiumPlus,
        'Geo': PartG.geo,
        'Geologica': PartG.geologica,
        'Georama': PartG.georama,
        'Geostar': PartG.geostar,
        'Geostar Fill': PartG.geostarFill,
        'Germania One': PartG.germaniaOne,
        'Gideon Roman': PartG.gideonRoman,
        'Gidugu': PartG.gidugu,
        'Gilda Display': PartG.gildaDisplay,
        'Girassol': PartG.girassol,
        'Give You Glory': PartG.giveYouGlory,
        'Glass Antiqua': PartG.glassAntiqua,
        'Glegoo': PartG.glegoo,
        'Gloock': PartG.gloock,
        'Gloria Hallelujah': PartG.gloriaHallelujah,
        'Glory': PartG.glory,
        'Gluten': PartG.gluten,
        'Goblin One': PartG.goblinOne,
        'Gochi Hand': PartG.gochiHand,
        'Goldman': PartG.goldman,
        'Golos Text': PartG.golosText,
        'Gorditas': PartG.gorditas,
        'Gothic A1': PartG.gothicA1,
        'Gotu': PartG.gotu,
        'Goudy Bookletter 1911': PartG.goudyBookletter1911,
        'Gowun Batang': PartG.gowunBatang,
        'Gowun Dodum': PartG.gowunDodum,
        'Graduate': PartG.graduate,
        'Grand Hotel': PartG.grandHotel,
        'Grandiflora One': PartG.grandifloraOne,
        'Grandstander': PartG.grandstander,
        'Grape Nuts': PartG.grapeNuts,
        'Gravitas One': PartG.gravitasOne,
        'Great Vibes': PartG.greatVibes,
        'Grechen Fuemen': PartG.grechenFuemen,
        'Grenze': PartG.grenze,
        'Grenze Gotisch': PartG.grenzeGotisch,
        'Grey Qo': PartG.greyQo,
        'Griffy': PartG.griffy,
        'Gruppo': PartG.gruppo,
        'Gudea': PartG.gudea,
        'Gugi': PartG.gugi,
        'Gulzar': PartG.gulzar,
        'Gupter': PartG.gupter,
        'Gurajada': PartG.gurajada,
        'Gwendolyn': PartG.gwendolyn,
        'Habibi': PartH.habibi,
        'Hachi Maru Pop': PartH.hachiMaruPop,
        'Hahmlet': PartH.hahmlet,
        'Halant': PartH.halant,
        'Hammersmith One': PartH.hammersmithOne,
        'Hanalei': PartH.hanalei,
        'Hanalei Fill': PartH.hanaleiFill,
        'Handjet': PartH.handjet,
        'Handlee': PartH.handlee,
        'Hanken Grotesk': PartH.hankenGrotesk,
        'Hanuman': PartH.hanuman,
        'Happy Monkey': PartH.happyMonkey,
        'Harmattan': PartH.harmattan,
        'Headland One': PartH.headlandOne,
        'Hedvig Letters Sans': PartH.hedvigLettersSans,
        'Hedvig Letters Serif': PartH.hedvigLettersSerif,
        'Heebo': PartH.heebo,
        'Henny Penny': PartH.hennyPenny,
        'Hepta Slab': PartH.heptaSlab,
        'Herr Von Muellerhoff': PartH.herrVonMuellerhoff,
        'Hi Melody': PartH.hiMelody,
        'Hina Mincho': PartH.hinaMincho,
        'Hind': PartH.hind,
        'Hind Guntur': PartH.hindGuntur,
        'Hind Madurai': PartH.hindMadurai,
        'Hind Siliguri': PartH.hindSiliguri,
        'Hind Vadodara': PartH.hindVadodara,
        'Holtwood One SC': PartH.holtwoodOneSc,
        'Homemade Apple': PartH.homemadeApple,
        'Homenaje': PartH.homenaje,
        'Honk': PartH.honk,
        'Hubballi': PartH.hubballi,
        'Hurricane': PartH.hurricane,
        'IBM Plex Mono': PartI.ibmPlexMono,
        'IBM Plex Sans': PartI.ibmPlexSans,
        'IBM Plex Sans Arabic': PartI.ibmPlexSansArabic,
        'IBM Plex Sans Condensed': PartI.ibmPlexSansCondensed,
        'IBM Plex Sans Devanagari': PartI.ibmPlexSansDevanagari,
        'IBM Plex Sans Hebrew': PartI.ibmPlexSansHebrew,
        'IBM Plex Sans JP': PartI.ibmPlexSansJp,
        'IBM Plex Sans KR': PartI.ibmPlexSansKr,
        'IBM Plex Sans Thai': PartI.ibmPlexSansThai,
        'IBM Plex Sans Thai Looped': PartI.ibmPlexSansThaiLooped,
        'IBM Plex Serif': PartI.ibmPlexSerif,
        'IM Fell DW Pica': PartI.imFellDwPica,
        'IM Fell DW Pica SC': PartI.imFellDwPicaSc,
        'IM Fell Double Pica': PartI.imFellDoublePica,
        'IM Fell Double Pica SC': PartI.imFellDoublePicaSc,
        'IM Fell English': PartI.imFellEnglish,
        'IM Fell English SC': PartI.imFellEnglishSc,
        'IM Fell French Canon': PartI.imFellFrenchCanon,
        'IM Fell French Canon SC': PartI.imFellFrenchCanonSc,
        'IM Fell Great Primer': PartI.imFellGreatPrimer,
        'IM Fell Great Primer SC': PartI.imFellGreatPrimerSc,
        'Ibarra Real Nova': PartI.ibarraRealNova,
        'Iceberg': PartI.iceberg,
        'Iceland': PartI.iceland,
        'Imbue': PartI.imbue,
        'Imperial Script': PartI.imperialScript,
        'Imprima': PartI.imprima,
        'Inclusive Sans': PartI.inclusiveSans,
        'Inconsolata': PartI.inconsolata,
        'Inder': PartI.inder,
        'Indie Flower': PartI.indieFlower,
        'Ingrid Darling': PartI.ingridDarling,
        'Inika': PartI.inika,
        'Inknut Antiqua': PartI.inknutAntiqua,
        'Inria Sans': PartI.inriaSans,
        'Inria Serif': PartI.inriaSerif,
        'Inspiration': PartI.inspiration,
        'Instrument Sans': PartI.instrumentSans,
        'Instrument Serif': PartI.instrumentSerif,
        'Inter': PartI.inter,
        'Inter Tight': PartI.interTight,
        'Irish Grover': PartI.irishGrover,
        'Island Moments': PartI.islandMoments,
        'Istok Web': PartI.istokWeb,
        'Italiana': PartI.italiana,
        'Italianno': PartI.italianno,
        'Itim': PartI.itim,
        'Jacquard 12': PartJ.jacquard12,
        'Jacquard 12 Charted': PartJ.jacquard12Charted,
        'Jacquard 24': PartJ.jacquard24,
        'Jacquard 24 Charted': PartJ.jacquard24Charted,
        'Jacquarda Bastarda 9': PartJ.jacquardaBastarda9,
        'Jacquarda Bastarda 9 Charted': PartJ.jacquardaBastarda9Charted,
        'Jacques Francois': PartJ.jacquesFrancois,
        'Jacques Francois Shadow': PartJ.jacquesFrancoisShadow,
        'Jaini': PartJ.jaini,
        'Jaini Purva': PartJ.jainiPurva,
        'Jaldi': PartJ.jaldi,
        'Jaro': PartJ.jaro,
        'Jersey 10': PartJ.jersey10,
        'Jersey 10 Charted': PartJ.jersey10Charted,
        'Jersey 15': PartJ.jersey15,
        'Jersey 15 Charted': PartJ.jersey15Charted,
        'Jersey 20': PartJ.jersey20,
        'Jersey 20 Charted': PartJ.jersey20Charted,
        'Jersey 25': PartJ.jersey25,
        'Jersey 25 Charted': PartJ.jersey25Charted,
        'JetBrains Mono': PartJ.jetBrainsMono,
        'Jim Nightshade': PartJ.jimNightshade,
        'Joan': PartJ.joan,
        'Jockey One': PartJ.jockeyOne,
        'Jolly Lodger': PartJ.jollyLodger,
        'Jomhuria': PartJ.jomhuria,
        'Jomolhari': PartJ.jomolhari,
        'Josefin Sans': PartJ.josefinSans,
        'Josefin Slab': PartJ.josefinSlab,
        'Jost': PartJ.jost,
        'Joti One': PartJ.jotiOne,
        'Jua': PartJ.jua,
        'Judson': PartJ.judson,
        'Julee': PartJ.julee,
        'Julius Sans One': PartJ.juliusSansOne,
        'Junge': PartJ.junge,
        'Jura': PartJ.jura,
        'Just Another Hand': PartJ.justAnotherHand,
        'Just Me Again Down Here': PartJ.justMeAgainDownHere,
        'K2D': PartK.k2d,
        'Kablammo': PartK.kablammo,
        'Kadwa': PartK.kadwa,
        'Kaisei Decol': PartK.kaiseiDecol,
        'Kaisei HarunoUmi': PartK.kaiseiHarunoUmi,
        'Kaisei Opti': PartK.kaiseiOpti,
        'Kaisei Tokumin': PartK.kaiseiTokumin,
        'Kalam': PartK.kalam,
        'Kalnia': PartK.kalnia,
        'Kalnia Glaze': PartK.kalniaGlaze,
        'Kameron': PartK.kameron,
        'Kanit': PartK.kanit,
        'Kantumruy Pro': PartK.kantumruyPro,
        'Karantina': PartK.karantina,
        'Karla': PartK.karla,
        'Karma': PartK.karma,
        'Katibeh': PartK.katibeh,
        'Kaushan Script': PartK.kaushanScript,
        'Kavivanar': PartK.kavivanar,
        'Kavoon': PartK.kavoon,
        'Kay Pho Du': PartK.kayPhoDu,
        'Kdam Thmor Pro': PartK.kdamThmorPro,
        'Keania One': PartK.keaniaOne,
        'Kelly Slab': PartK.kellySlab,
        'Kenia': PartK.kenia,
        'Khand': PartK.khand,
        'Khmer': PartK.khmer,
        'Khula': PartK.khula,
        'Kings': PartK.kings,
        'Kirang Haerang': PartK.kirangHaerang,
        'Kite One': PartK.kiteOne,
        'Kiwi Maru': PartK.kiwiMaru,
        'Klee One': PartK.kleeOne,
        'Knewave': PartK.knewave,
        'KoHo': PartK.koHo,
        'Kodchasan': PartK.kodchasan,
        'Kode Mono': PartK.kodeMono,
        'Koh Santepheap': PartK.kohSantepheap,
        'Kolker Brush': PartK.kolkerBrush,
        'Konkhmer Sleokchher': PartK.konkhmerSleokchher,
        'Kosugi': PartK.kosugi,
        'Kosugi Maru': PartK.kosugiMaru,
        'Kotta One': PartK.kottaOne,
        'Koulen': PartK.koulen,
        'Kranky': PartK.kranky,
        'Kreon': PartK.kreon,
        'Kristi': PartK.kristi,
        'Krona One': PartK.kronaOne,
        'Krub': PartK.krub,
        'Kufam': PartK.kufam,
        'Kulim Park': PartK.kulimPark,
        'Kumar One': PartK.kumarOne,
        'Kumar One Outline': PartK.kumarOneOutline,
        'Kumbh Sans': PartK.kumbhSans,
        'Kurale': PartK.kurale,
        'LXGW WenKai Mono TC': PartL.lxgwWenKaiMonoTc,
        'LXGW WenKai TC': PartL.lxgwWenKaiTc,
        'La Belle Aurore': PartL.laBelleAurore,
        'Labrada': PartL.labrada,
        'Lacquer': PartL.lacquer,
        'Laila': PartL.laila,
        'Lakki Reddy': PartL.lakkiReddy,
        'Lalezar': PartL.lalezar,
        'Lancelot': PartL.lancelot,
        'Langar': PartL.langar,
        'Lateef': PartL.lateef,
        'Lato': PartL.lato,
        'Lavishly Yours': PartL.lavishlyYours,
        'League Gothic': PartL.leagueGothic,
        'League Script': PartL.leagueScript,
        'League Spartan': PartL.leagueSpartan,
        'Leckerli One': PartL.leckerliOne,
        'Ledger': PartL.ledger,
        'Lekton': PartL.lekton,
        'Lemon': PartL.lemon,
        'Lemonada': PartL.lemonada,
        'Lexend': PartL.lexend,
        'Lexend Deca': PartL.lexendDeca,
        'Lexend Exa': PartL.lexendExa,
        'Lexend Giga': PartL.lexendGiga,
        'Lexend Mega': PartL.lexendMega,
        'Lexend Peta': PartL.lexendPeta,
        'Lexend Tera': PartL.lexendTera,
        'Lexend Zetta': PartL.lexendZetta,
        'Libre Barcode 128': PartL.libreBarcode128,
        'Libre Barcode 128 Text': PartL.libreBarcode128Text,
        'Libre Barcode 39': PartL.libreBarcode39,
        'Libre Barcode 39 Extended': PartL.libreBarcode39Extended,
        'Libre Barcode 39 Extended Text': PartL.libreBarcode39ExtendedText,
        'Libre Barcode 39 Text': PartL.libreBarcode39Text,
        'Libre Barcode EAN13 Text': PartL.libreBarcodeEan13Text,
        'Libre Baskerville': PartL.libreBaskerville,
        'Libre Bodoni': PartL.libreBodoni,
        'Libre Caslon Display': PartL.libreCaslonDisplay,
        'Libre Caslon Text': PartL.libreCaslonText,
        'Libre Franklin': PartL.libreFranklin,
        'Licorice': PartL.licorice,
        'Life Savers': PartL.lifeSavers,
        'Lilita One': PartL.lilitaOne,
        'Lily Script One': PartL.lilyScriptOne,
        'Limelight': PartL.limelight,
        'Linden Hill': PartL.lindenHill,
        'Linefont': PartL.linefont,
        'Lisu Bosa': PartL.lisuBosa,
        'Literata': PartL.literata,
        'Liu Jian Mao Cao': PartL.liuJianMaoCao,
        'Livvic': PartL.livvic,
        'Lobster': PartL.lobster,
        'Lobster Two': PartL.lobsterTwo,
        'Londrina Outline': PartL.londrinaOutline,
        'Londrina Shadow': PartL.londrinaShadow,
        'Londrina Sketch': PartL.londrinaSketch,
        'Londrina Solid': PartL.londrinaSolid,
        'Long Cang': PartL.longCang,
        'Lora': PartL.lora,
        'Love Light': PartL.loveLight,
        'Love Ya Like A Sister': PartL.loveYaLikeASister,
        'Loved by the King': PartL.lovedByTheKing,
        'Lovers Quarrel': PartL.loversQuarrel,
        'Luckiest Guy': PartL.luckiestGuy,
        'Lugrasimo': PartL.lugrasimo,
        'Lumanosimo': PartL.lumanosimo,
        'Lunasima': PartL.lunasima,
        'Lusitana': PartL.lusitana,
        'Lustria': PartL.lustria,
        'Luxurious Roman': PartL.luxuriousRoman,
        'Luxurious Script': PartL.luxuriousScript,
        'M PLUS 1': PartM.mPlus1,
        'M PLUS 1 Code': PartM.mPlus1Code,
        'M PLUS 1p': PartM.mPlus1p,
        'M PLUS 2': PartM.mPlus2,
        'M PLUS Code Latin': PartM.mPlusCodeLatin,
        'M PLUS Rounded 1c': PartM.mPlusRounded1c,
        'Ma Shan Zheng': PartM.maShanZheng,
        'Macondo': PartM.macondo,
        'Macondo Swash Caps': PartM.macondoSwashCaps,
        'Mada': PartM.mada,
        'Madimi One': PartM.madimiOne,
        'Magra': PartM.magra,
        'Maiden Orange': PartM.maidenOrange,
        'Maitree': PartM.maitree,
        'Major Mono Display': PartM.majorMonoDisplay,
        'Mako': PartM.mako,
        'Mali': PartM.mali,
        'Mallanna': PartM.mallanna,
        'Maname': PartM.maname,
        'Mandali': PartM.mandali,
        'Manjari': PartM.manjari,
        'Manrope': PartM.manrope,
        'Mansalva': PartM.mansalva,
        'Manuale': PartM.manuale,
        'Marcellus': PartM.marcellus,
        'Marcellus SC': PartM.marcellusSc,
        'Marck Script': PartM.marckScript,
        'Margarine': PartM.margarine,
        'Marhey': PartM.marhey,
        'Markazi Text': PartM.markaziText,
        'Marko One': PartM.markoOne,
        'Marmelad': PartM.marmelad,
        'Martel': PartM.martel,
        'Martel Sans': PartM.martelSans,
        'Martian Mono': PartM.martianMono,
        'Marvel': PartM.marvel,
        'Mate': PartM.mate,
        'Mate SC': PartM.mateSc,
        'Maven Pro': PartM.mavenPro,
        'McLaren': PartM.mcLaren,
        'Mea Culpa': PartM.meaCulpa,
        'Meddon': PartM.meddon,
        'MedievalSharp': PartM.medievalSharp,
        'Medula One': PartM.medulaOne,
        'Meera Inimai': PartM.meeraInimai,
        'Megrim': PartM.megrim,
        'Meie Script': PartM.meieScript,
        'Meow Script': PartM.meowScript,
        'Merienda': PartM.merienda,
        'Merriweather': PartM.merriweather,
        'Merriweather Sans': PartM.merriweatherSans,
        'Metal': PartM.metal,
        'Metal Mania': PartM.metalMania,
        'Metamorphous': PartM.metamorphous,
        'Metrophobic': PartM.metrophobic,
        'Michroma': PartM.michroma,
        'Micro 5': PartM.micro5,
        'Micro 5 Charted': PartM.micro5Charted,
        'Milonga': PartM.milonga,
        'Miltonian': PartM.miltonian,
        'Miltonian Tattoo': PartM.miltonianTattoo,
        'Mina': PartM.mina,
        'Mingzat': PartM.mingzat,
        'Miniver': PartM.miniver,
        'Miriam Libre': PartM.miriamLibre,
        'Mirza': PartM.mirza,
        'Miss Fajardose': PartM.missFajardose,
        'Mitr': PartM.mitr,
        'Mochiy Pop One': PartM.mochiyPopOne,
        'Mochiy Pop P One': PartM.mochiyPopPOne,
        'Modak': PartM.modak,
        'Modern Antiqua': PartM.modernAntiqua,
        'Mogra': PartM.mogra,
        'Mohave': PartM.mohave,
        'Moirai One': PartM.moiraiOne,
        'Molengo': PartM.molengo,
        'Molle': PartM.molle,
        'Monda': PartM.monda,
        'Monofett': PartM.monofett,
        'Monomaniac One': PartM.monomaniacOne,
        'Monoton': PartM.monoton,
        'Monsieur La Doulaise': PartM.monsieurLaDoulaise,
        'Montaga': PartM.montaga,
        'Montagu Slab': PartM.montaguSlab,
        'MonteCarlo': PartM.monteCarlo,
        'Montez': PartM.montez,
        'Montserrat': PartM.montserrat,
        'Montserrat Alternates': PartM.montserratAlternates,
        'Montserrat Subrayada': PartM.montserratSubrayada,
        'Moo Lah Lah': PartM.mooLahLah,
        'Mooli': PartM.mooli,
        'Moon Dance': PartM.moonDance,
        'Moul': PartM.moul,
        'Moulpali': PartM.moulpali,
        'Mountains of Christmas': PartM.mountainsOfChristmas,
        'Mouse Memoirs': PartM.mouseMemoirs,
        'Mr Bedfort': PartM.mrBedfort,
        'Mr Dafoe': PartM.mrDafoe,
        'Mr De Haviland': PartM.mrDeHaviland,
        'Mrs Saint Delafield': PartM.mrsSaintDelafield,
        'Mrs Sheppards': PartM.mrsSheppards,
        'Ms Madi': PartM.msMadi,
        'Mukta': PartM.mukta,
        'Mukta Mahee': PartM.muktaMahee,
        'Mukta Malar': PartM.muktaMalar,
        'Mukta Vaani': PartM.muktaVaani,
        'Mulish': PartM.mulish,
        'Murecho': PartM.murecho,
        'MuseoModerno': PartM.museoModerno,
        'My Soul': PartM.mySoul,
        'Mynerve': PartM.mynerve,
        'Mystery Quest': PartM.mysteryQuest,
        'NTR': PartN.ntr,
        'Nabla': PartN.nabla,
        'Namdhinggo': PartN.namdhinggo,
        'Nanum Brush Script': PartN.nanumBrushScript,
        'Nanum Gothic': PartN.nanumGothic,
        'Nanum Gothic Coding': PartN.nanumGothicCoding,
        'Nanum Myeongjo': PartN.nanumMyeongjo,
        'Nanum Pen Script': PartN.nanumPenScript,
        'Narnoor': PartN.narnoor,
        'Neonderthaw': PartN.neonderthaw,
        'Nerko One': PartN.nerkoOne,
        'Neucha': PartN.neucha,
        'Neuton': PartN.neuton,
        'New Rocker': PartN.newRocker,
        'New Tegomin': PartN.newTegomin,
        'News Cycle': PartN.newsCycle,
        'Newsreader': PartN.newsreader,
        'Niconne': PartN.niconne,
        'Niramit': PartN.niramit,
        'Nixie One': PartN.nixieOne,
        'Nobile': PartN.nobile,
        'Nokora': PartN.nokora,
        'Norican': PartN.norican,
        'Nosifer': PartN.nosifer,
        'Notable': PartN.notable,
        'Nothing You Could Do': PartN.nothingYouCouldDo,
        'Noticia Text': PartN.noticiaText,
        'Noto Color Emoji': PartN.notoColorEmoji,
        'Noto Emoji': PartN.notoEmoji,
        'Noto Kufi Arabic': PartN.notoKufiArabic,
        'Noto Music': PartN.notoMusic,
        'Noto Naskh Arabic': PartN.notoNaskhArabic,
        'Noto Nastaliq Urdu': PartN.notoNastaliqUrdu,
        'Noto Rashi Hebrew': PartN.notoRashiHebrew,
        'Noto Sans': PartN.notoSans,
        'Noto Sans Adlam': PartN.notoSansAdlam,
        'Noto Sans Adlam Unjoined': PartN.notoSansAdlamUnjoined,
        'Noto Sans Anatolian Hieroglyphs': PartN.notoSansAnatolianHieroglyphs,
        'Noto Sans Arabic': PartN.notoSansArabic,
        'Noto Sans Armenian': PartN.notoSansArmenian,
        'Noto Sans Avestan': PartN.notoSansAvestan,
        'Noto Sans Balinese': PartN.notoSansBalinese,
        'Noto Sans Bamum': PartN.notoSansBamum,
        'Noto Sans Bassa Vah': PartN.notoSansBassaVah,
        'Noto Sans Batak': PartN.notoSansBatak,
        'Noto Sans Bengali': PartN.notoSansBengali,
        'Noto Sans Bhaiksuki': PartN.notoSansBhaiksuki,
        'Noto Sans Brahmi': PartN.notoSansBrahmi,
        'Noto Sans Buginese': PartN.notoSansBuginese,
        'Noto Sans Buhid': PartN.notoSansBuhid,
        'Noto Sans Canadian Aboriginal': PartN.notoSansCanadianAboriginal,
        'Noto Sans Carian': PartN.notoSansCarian,
        'Noto Sans Caucasian Albanian': PartN.notoSansCaucasianAlbanian,
        'Noto Sans Chakma': PartN.notoSansChakma,
        'Noto Sans Cham': PartN.notoSansCham,
        'Noto Sans Cherokee': PartN.notoSansCherokee,
        'Noto Sans Chorasmian': PartN.notoSansChorasmian,
        'Noto Sans Coptic': PartN.notoSansCoptic,
        'Noto Sans Cuneiform': PartN.notoSansCuneiform,
        'Noto Sans Cypriot': PartN.notoSansCypriot,
        'Noto Sans Cypro Minoan': PartN.notoSansCyproMinoan,
        'Noto Sans Deseret': PartN.notoSansDeseret,
        'Noto Sans Devanagari': PartN.notoSansDevanagari,
        'Noto Sans Display': PartN.notoSansDisplay,
        'Noto Sans Duployan': PartN.notoSansDuployan,
        'Noto Sans Egyptian Hieroglyphs': PartN.notoSansEgyptianHieroglyphs,
        'Noto Sans Elbasan': PartN.notoSansElbasan,
        'Noto Sans Elymaic': PartN.notoSansElymaic,
        'Noto Sans Ethiopic': PartN.notoSansEthiopic,
        'Noto Sans Georgian': PartN.notoSansGeorgian,
        'Noto Sans Glagolitic': PartN.notoSansGlagolitic,
        'Noto Sans Gothic': PartN.notoSansGothic,
        'Noto Sans Grantha': PartN.notoSansGrantha,
        'Noto Sans Gujarati': PartN.notoSansGujarati,
        'Noto Sans Gunjala Gondi': PartN.notoSansGunjalaGondi,
        'Noto Sans Gurmukhi': PartN.notoSansGurmukhi,
        'Noto Sans HK': PartN.notoSansHk,
        'Noto Sans Hanifi Rohingya': PartN.notoSansHanifiRohingya,
        'Noto Sans Hanunoo': PartN.notoSansHanunoo,
        'Noto Sans Hatran': PartN.notoSansHatran,
        'Noto Sans Hebrew': PartN.notoSansHebrew,
        'Noto Sans Imperial Aramaic': PartN.notoSansImperialAramaic,
        'Noto Sans Indic Siyaq Numbers': PartN.notoSansIndicSiyaqNumbers,
        'Noto Sans Inscriptional Pahlavi': PartN.notoSansInscriptionalPahlavi,
        'Noto Sans Inscriptional Parthian': PartN.notoSansInscriptionalParthian,
        'Noto Sans JP': PartN.notoSansJp,
        'Noto Sans Javanese': PartN.notoSansJavanese,
        'Noto Sans KR': PartN.notoSansKr,
        'Noto Sans Kaithi': PartN.notoSansKaithi,
        'Noto Sans Kannada': PartN.notoSansKannada,
        'Noto Sans Kawi': PartN.notoSansKawi,
        'Noto Sans Kayah Li': PartN.notoSansKayahLi,
        'Noto Sans Kharoshthi': PartN.notoSansKharoshthi,
        'Noto Sans Khmer': PartN.notoSansKhmer,
        'Noto Sans Khojki': PartN.notoSansKhojki,
        'Noto Sans Khudawadi': PartN.notoSansKhudawadi,
        'Noto Sans Lao': PartN.notoSansLao,
        'Noto Sans Lao Looped': PartN.notoSansLaoLooped,
        'Noto Sans Lepcha': PartN.notoSansLepcha,
        'Noto Sans Limbu': PartN.notoSansLimbu,
        'Noto Sans Linear A': PartN.notoSansLinearA,
        'Noto Sans Linear B': PartN.notoSansLinearB,
        'Noto Sans Lisu': PartN.notoSansLisu,
        'Noto Sans Lycian': PartN.notoSansLycian,
        'Noto Sans Lydian': PartN.notoSansLydian,
        'Noto Sans Mahajani': PartN.notoSansMahajani,
        'Noto Sans Malayalam': PartN.notoSansMalayalam,
        'Noto Sans Mandaic': PartN.notoSansMandaic,
        'Noto Sans Manichaean': PartN.notoSansManichaean,
        'Noto Sans Marchen': PartN.notoSansMarchen,
        'Noto Sans Masaram Gondi': PartN.notoSansMasaramGondi,
        'Noto Sans Math': PartN.notoSansMath,
        'Noto Sans Mayan Numerals': PartN.notoSansMayanNumerals,
        'Noto Sans Medefaidrin': PartN.notoSansMedefaidrin,
        'Noto Sans Meetei Mayek': PartN.notoSansMeeteiMayek,
        'Noto Sans Mende Kikakui': PartN.notoSansMendeKikakui,
        'Noto Sans Meroitic': PartN.notoSansMeroitic,
        'Noto Sans Miao': PartN.notoSansMiao,
        'Noto Sans Modi': PartN.notoSansModi,
        'Noto Sans Mongolian': PartN.notoSansMongolian,
        'Noto Sans Mono': PartN.notoSansMono,
        'Noto Sans Mro': PartN.notoSansMro,
        'Noto Sans Multani': PartN.notoSansMultani,
        'Noto Sans Myanmar': PartN.notoSansMyanmar,
        'Noto Sans NKo': PartN.notoSansNKo,
        'Noto Sans NKo Unjoined': PartN.notoSansNKoUnjoined,
        'Noto Sans Nabataean': PartN.notoSansNabataean,
        'Noto Sans Nag Mundari': PartN.notoSansNagMundari,
        'Noto Sans Nandinagari': PartN.notoSansNandinagari,
        'Noto Sans New Tai Lue': PartN.notoSansNewTaiLue,
        'Noto Sans Newa': PartN.notoSansNewa,
        'Noto Sans Nushu': PartN.notoSansNushu,
        'Noto Sans Ogham': PartN.notoSansOgham,
        'Noto Sans Ol Chiki': PartN.notoSansOlChiki,
        'Noto Sans Old Hungarian': PartN.notoSansOldHungarian,
        'Noto Sans Old Italic': PartN.notoSansOldItalic,
        'Noto Sans Old North Arabian': PartN.notoSansOldNorthArabian,
        'Noto Sans Old Permic': PartN.notoSansOldPermic,
        'Noto Sans Old Persian': PartN.notoSansOldPersian,
        'Noto Sans Old Sogdian': PartN.notoSansOldSogdian,
        'Noto Sans Old South Arabian': PartN.notoSansOldSouthArabian,
        'Noto Sans Old Turkic': PartN.notoSansOldTurkic,
        'Noto Sans Oriya': PartN.notoSansOriya,
        'Noto Sans Osage': PartN.notoSansOsage,
        'Noto Sans Osmanya': PartN.notoSansOsmanya,
        'Noto Sans Pahawh Hmong': PartN.notoSansPahawhHmong,
        'Noto Sans Palmyrene': PartN.notoSansPalmyrene,
        'Noto Sans Pau Cin Hau': PartN.notoSansPauCinHau,
        'Noto Sans Phags Pa': PartN.notoSansPhagsPa,
        'Noto Sans Phoenician': PartN.notoSansPhoenician,
        'Noto Sans Psalter Pahlavi': PartN.notoSansPsalterPahlavi,
        'Noto Sans Rejang': PartN.notoSansRejang,
        'Noto Sans Runic': PartN.notoSansRunic,
        'Noto Sans SC': PartN.notoSansSc,
        'Noto Sans Samaritan': PartN.notoSansSamaritan,
        'Noto Sans Saurashtra': PartN.notoSansSaurashtra,
        'Noto Sans Sharada': PartN.notoSansSharada,
        'Noto Sans Shavian': PartN.notoSansShavian,
        'Noto Sans Siddham': PartN.notoSansSiddham,
        'Noto Sans SignWriting': PartN.notoSansSignWriting,
        'Noto Sans Sinhala': PartN.notoSansSinhala,
        'Noto Sans Sogdian': PartN.notoSansSogdian,
        'Noto Sans Sora Sompeng': PartN.notoSansSoraSompeng,
        'Noto Sans Soyombo': PartN.notoSansSoyombo,
        'Noto Sans Sundanese': PartN.notoSansSundanese,
        'Noto Sans Syloti Nagri': PartN.notoSansSylotiNagri,
        'Noto Sans Symbols': PartN.notoSansSymbols,
        'Noto Sans Symbols 2': PartN.notoSansSymbols2,
        'Noto Sans Syriac': PartN.notoSansSyriac,
        'Noto Sans Syriac Eastern': PartN.notoSansSyriacEastern,
        'Noto Sans TC': PartN.notoSansTc,
        'Noto Sans Tagalog': PartN.notoSansTagalog,
        'Noto Sans Tagbanwa': PartN.notoSansTagbanwa,
        'Noto Sans Tai Le': PartN.notoSansTaiLe,
        'Noto Sans Tai Tham': PartN.notoSansTaiTham,
        'Noto Sans Tai Viet': PartN.notoSansTaiViet,
        'Noto Sans Takri': PartN.notoSansTakri,
        'Noto Sans Tamil': PartN.notoSansTamil,
        'Noto Sans Tamil Supplement': PartN.notoSansTamilSupplement,
        'Noto Sans Tangsa': PartN.notoSansTangsa,
        'Noto Sans Telugu': PartN.notoSansTelugu,
        'Noto Sans Thaana': PartN.notoSansThaana,
        'Noto Sans Thai': PartN.notoSansThai,
        'Noto Sans Thai Looped': PartN.notoSansThaiLooped,
        'Noto Sans Tifinagh': PartN.notoSansTifinagh,
        'Noto Sans Tirhuta': PartN.notoSansTirhuta,
        'Noto Sans Ugaritic': PartN.notoSansUgaritic,
        'Noto Sans Vai': PartN.notoSansVai,
        'Noto Sans Vithkuqi': PartN.notoSansVithkuqi,
        'Noto Sans Wancho': PartN.notoSansWancho,
        'Noto Sans Warang Citi': PartN.notoSansWarangCiti,
        'Noto Sans Yi': PartN.notoSansYi,
        'Noto Sans Zanabazar Square': PartN.notoSansZanabazarSquare,
        'Noto Serif': PartN.notoSerif,
        'Noto Serif Ahom': PartN.notoSerifAhom,
        'Noto Serif Armenian': PartN.notoSerifArmenian,
        'Noto Serif Balinese': PartN.notoSerifBalinese,
        'Noto Serif Bengali': PartN.notoSerifBengali,
        'Noto Serif Devanagari': PartN.notoSerifDevanagari,
        'Noto Serif Display': PartN.notoSerifDisplay,
        'Noto Serif Dogra': PartN.notoSerifDogra,
        'Noto Serif Ethiopic': PartN.notoSerifEthiopic,
        'Noto Serif Georgian': PartN.notoSerifGeorgian,
        'Noto Serif Grantha': PartN.notoSerifGrantha,
        'Noto Serif Gujarati': PartN.notoSerifGujarati,
        'Noto Serif Gurmukhi': PartN.notoSerifGurmukhi,
        'Noto Serif HK': PartN.notoSerifHk,
        'Noto Serif Hebrew': PartN.notoSerifHebrew,
        'Noto Serif JP': PartN.notoSerifJp,
        'Noto Serif KR': PartN.notoSerifKr,
        'Noto Serif Kannada': PartN.notoSerifKannada,
        'Noto Serif Khitan Small Script': PartN.notoSerifKhitanSmallScript,
        'Noto Serif Khmer': PartN.notoSerifKhmer,
        'Noto Serif Khojki': PartN.notoSerifKhojki,
        'Noto Serif Lao': PartN.notoSerifLao,
        'Noto Serif Makasar': PartN.notoSerifMakasar,
        'Noto Serif Malayalam': PartN.notoSerifMalayalam,
        'Noto Serif Myanmar': PartN.notoSerifMyanmar,
        'Noto Serif NP Hmong': PartN.notoSerifNpHmong,
        'Noto Serif Old Uyghur': PartN.notoSerifOldUyghur,
        'Noto Serif Oriya': PartN.notoSerifOriya,
        'Noto Serif Ottoman Siyaq': PartN.notoSerifOttomanSiyaq,
        'Noto Serif SC': PartN.notoSerifSc,
        'Noto Serif Sinhala': PartN.notoSerifSinhala,
        'Noto Serif TC': PartN.notoSerifTc,
        'Noto Serif Tamil': PartN.notoSerifTamil,
        'Noto Serif Tangut': PartN.notoSerifTangut,
        'Noto Serif Telugu': PartN.notoSerifTelugu,
        'Noto Serif Thai': PartN.notoSerifThai,
        'Noto Serif Tibetan': PartN.notoSerifTibetan,
        'Noto Serif Toto': PartN.notoSerifToto,
        'Noto Serif Vithkuqi': PartN.notoSerifVithkuqi,
        'Noto Serif Yezidi': PartN.notoSerifYezidi,
        'Noto Traditional Nushu': PartN.notoTraditionalNushu,
        'Noto Znamenny Musical Notation': PartN.notoZnamennyMusicalNotation,
        'Nova Cut': PartN.novaCut,
        'Nova Flat': PartN.novaFlat,
        'Nova Mono': PartN.novaMono,
        'Nova Oval': PartN.novaOval,
        'Nova Round': PartN.novaRound,
        'Nova Script': PartN.novaScript,
        'Nova Slim': PartN.novaSlim,
        'Nova Square': PartN.novaSquare,
        'Numans': PartN.numans,
        'Nunito': PartN.nunito,
        'Nunito Sans': PartN.nunitoSans,
        'Nuosu SIL': PartN.nuosuSil,
        'Odibee Sans': PartO.odibeeSans,
        'Odor Mean Chey': PartO.odorMeanChey,
        'Offside': PartO.offside,
        'Oi': PartO.oi,
        'Ojuju': PartO.ojuju,
        'Old Standard TT': PartO.oldStandardTt,
        'Oldenburg': PartO.oldenburg,
        'Ole': PartO.ole,
        'Oleo Script': PartO.oleoScript,
        'Oleo Script Swash Caps': PartO.oleoScriptSwashCaps,
        'Onest': PartO.onest,
        'Oooh Baby': PartO.ooohBaby,
        'Open Sans': PartO.openSans,
        'Open Sans Condensed': PartO.openSansCondensed,
        'Oranienbaum': PartO.oranienbaum,
        'Orbit': PartO.orbit,
        'Orbitron': PartO.orbitron,
        'Oregano': PartO.oregano,
        'Orelega One': PartO.orelegaOne,
        'Orienta': PartO.orienta,
        'Original Surfer': PartO.originalSurfer,
        'Oswald': PartO.oswald,
        'Outfit': PartO.outfit,
        'Over the Rainbow': PartO.overTheRainbow,
        'Overlock': PartO.overlock,
        'Overlock SC': PartO.overlockSc,
        'Overpass': PartO.overpass,
        'Overpass Mono': PartO.overpassMono,
        'Ovo': PartO.ovo,
        'Oxanium': PartO.oxanium,
        'Oxygen': PartO.oxygen,
        'Oxygen Mono': PartO.oxygenMono,
        'PT Mono': PartP.ptMono,
        'PT Sans': PartP.ptSans,
        'PT Sans Caption': PartP.ptSansCaption,
        'PT Sans Narrow': PartP.ptSansNarrow,
        'PT Serif': PartP.ptSerif,
        'PT Serif Caption': PartP.ptSerifCaption,
        'Pacifico': PartP.pacifico,
        'Padauk': PartP.padauk,
        'Padyakke Expanded One': PartP.padyakkeExpandedOne,
        'Palanquin': PartP.palanquin,
        'Palanquin Dark': PartP.palanquinDark,
        'Palette Mosaic': PartP.paletteMosaic,
        'Pangolin': PartP.pangolin,
        'Paprika': PartP.paprika,
        'Parisienne': PartP.parisienne,
        'Passero One': PartP.passeroOne,
        'Passion One': PartP.passionOne,
        'Passions Conflict': PartP.passionsConflict,
        'Pathway Extreme': PartP.pathwayExtreme,
        'Pathway Gothic One': PartP.pathwayGothicOne,
        'Patrick Hand': PartP.patrickHand,
        'Patrick Hand SC': PartP.patrickHandSc,
        'Pattaya': PartP.pattaya,
        'Patua One': PartP.patuaOne,
        'Pavanam': PartP.pavanam,
        'Paytone One': PartP.paytoneOne,
        'Peddana': PartP.peddana,
        'Peralta': PartP.peralta,
        'Permanent Marker': PartP.permanentMarker,
        'Petemoss': PartP.petemoss,
        'Petit Formal Script': PartP.petitFormalScript,
        'Petrona': PartP.petrona,
        'Philosopher': PartP.philosopher,
        'Phudu': PartP.phudu,
        'Piazzolla': PartP.piazzolla,
        'Piedra': PartP.piedra,
        'Pinyon Script': PartP.pinyonScript,
        'Pirata One': PartP.pirataOne,
        'Pixelify Sans': PartP.pixelifySans,
        'Plaster': PartP.plaster,
        'Platypi': PartP.platypi,
        'Play': PartP.play,
        'Playball': PartP.playball,
        'Playfair': PartP.playfair,
        'Playfair Display': PartP.playfairDisplay,
        'Playfair Display SC': PartP.playfairDisplaySc,
        'Playpen Sans': PartP.playpenSans,
        'Playwrite AR': PartP.playwriteAr,
        'Playwrite AT': PartP.playwriteAt,
        'Playwrite AU NSW': PartP.playwriteAuNsw,
        'Playwrite AU QLD': PartP.playwriteAuQld,
        'Playwrite AU SA': PartP.playwriteAuSa,
        'Playwrite AU TAS': PartP.playwriteAuTas,
        'Playwrite AU VIC': PartP.playwriteAuVic,
        'Playwrite BE VLG': PartP.playwriteBeVlg,
        'Playwrite BE WAL': PartP.playwriteBeWal,
        'Playwrite BR': PartP.playwriteBr,
        'Playwrite CA': PartP.playwriteCa,
        'Playwrite CL': PartP.playwriteCl,
        'Playwrite CO': PartP.playwriteCo,
        'Playwrite CU': PartP.playwriteCu,
        'Playwrite CZ': PartP.playwriteCz,
        'Playwrite DE Grund': PartP.playwriteDeGrund,
        'Playwrite DE LA': PartP.playwriteDeLa,
        'Playwrite DE SAS': PartP.playwriteDeSas,
        'Playwrite DE VA': PartP.playwriteDeVa,
        'Playwrite DK Loopet': PartP.playwriteDkLoopet,
        'Playwrite DK Uloopet': PartP.playwriteDkUloopet,
        'Playwrite ES': PartP.playwriteEs,
        'Playwrite ES Deco': PartP.playwriteEsDeco,
        'Playwrite FR Moderne': PartP.playwriteFrModerne,
        'Playwrite FR Trad': PartP.playwriteFrTrad,
        'Playwrite GB J': PartP.playwriteGbJ,
        'Playwrite GB S': PartP.playwriteGbS,
        'Playwrite HR': PartP.playwriteHr,
        'Playwrite HR Lijeva': PartP.playwriteHrLijeva,
        'Playwrite HU': PartP.playwriteHu,
        'Playwrite ID': PartP.playwriteId,
        'Playwrite IE': PartP.playwriteIe,
        'Playwrite IN': PartP.playwriteIn,
        'Playwrite IS': PartP.playwriteIs,
        'Playwrite IT Moderna': PartP.playwriteItModerna,
        'Playwrite IT Trad': PartP.playwriteItTrad,
        'Playwrite MX': PartP.playwriteMx,
        'Playwrite NG Modern': PartP.playwriteNgModern,
        'Playwrite NL': PartP.playwriteNl,
        'Playwrite NO': PartP.playwriteNo,
        'Playwrite NZ': PartP.playwriteNz,
        'Playwrite PE': PartP.playwritePe,
        'Playwrite PL': PartP.playwritePl,
        'Playwrite PT': PartP.playwritePt,
        'Playwrite RO': PartP.playwriteRo,
        'Playwrite SK': PartP.playwriteSk,
        'Playwrite TZ': PartP.playwriteTz,
        'Playwrite US Modern': PartP.playwriteUsModern,
        'Playwrite US Trad': PartP.playwriteUsTrad,
        'Playwrite VN': PartP.playwriteVn,
        'Playwrite ZA': PartP.playwriteZa,
        'Plus Jakarta Sans': PartP.plusJakartaSans,
        'Podkova': PartP.podkova,
        'Poetsen One': PartP.poetsenOne,
        'Poiret One': PartP.poiretOne,
        'Poller One': PartP.pollerOne,
        'Poltawski Nowy': PartP.poltawskiNowy,
        'Poly': PartP.poly,
        'Pompiere': PartP.pompiere,
        'Pontano Sans': PartP.pontanoSans,
        'Poor Story': PartP.poorStory,
        'Poppins': PartP.poppins,
        'Port Lligat Sans': PartP.portLligatSans,
        'Port Lligat Slab': PartP.portLligatSlab,
        'Potta One': PartP.pottaOne,
        'Pragati Narrow': PartP.pragatiNarrow,
        'Praise': PartP.praise,
        'Prata': PartP.prata,
        'Preahvihear': PartP.preahvihear,
        'Press Start 2P': PartP.pressStart2p,
        'Pridi': PartP.pridi,
        'Princess Sofia': PartP.princessSofia,
        'Prociono': PartP.prociono,
        'Prompt': PartP.prompt,
        'Prosto One': PartP.prostoOne,
        'Protest Guerrilla': PartP.protestGuerrilla,
        'Protest Revolution': PartP.protestRevolution,
        'Protest Riot': PartP.protestRiot,
        'Protest Strike': PartP.protestStrike,
        'Proza Libre': PartP.prozaLibre,
        'Public Sans': PartP.publicSans,
        'Puppies Play': PartP.puppiesPlay,
        'Puritan': PartP.puritan,
        'Purple Purse': PartP.purplePurse,
        'Qahiri': PartQ.qahiri,
        'Quando': PartQ.quando,
        'Quantico': PartQ.quantico,
        'Quattrocento': PartQ.quattrocento,
        'Quattrocento Sans': PartQ.quattrocentoSans,
        'Questrial': PartQ.questrial,
        'Quicksand': PartQ.quicksand,
        'Quintessential': PartQ.quintessential,
        'Qwigley': PartQ.qwigley,
        'Qwitcher Grypen': PartQ.qwitcherGrypen,
        'REM': PartR.rem,
        'Racing Sans One': PartR.racingSansOne,
        'Radio Canada': PartR.radioCanada,
        'Radio Canada Big': PartR.radioCanadaBig,
        'Radley': PartR.radley,
        'Rajdhani': PartR.rajdhani,
        'Rakkas': PartR.rakkas,
        'Raleway': PartR.raleway,
        'Raleway Dots': PartR.ralewayDots,
        'Ramabhadra': PartR.ramabhadra,
        'Ramaraja': PartR.ramaraja,
        'Rambla': PartR.rambla,
        'Rammetto One': PartR.rammettoOne,
        'Rampart One': PartR.rampartOne,
        'Ranchers': PartR.ranchers,
        'Rancho': PartR.rancho,
        'Ranga': PartR.ranga,
        'Rasa': PartR.rasa,
        'Rationale': PartR.rationale,
        'Ravi Prakash': PartR.raviPrakash,
        'Readex Pro': PartR.readexPro,
        'Recursive': PartR.recursive,
        'Red Hat Display': PartR.redHatDisplay,
        'Red Hat Mono': PartR.redHatMono,
        'Red Hat Text': PartR.redHatText,
        'Red Rose': PartR.redRose,
        'Redacted': PartR.redacted,
        'Redacted Script': PartR.redactedScript,
        'Reddit Mono': PartR.redditMono,
        'Reddit Sans': PartR.redditSans,
        'Reddit Sans Condensed': PartR.redditSansCondensed,
        'Redressed': PartR.redressed,
        'Reem Kufi': PartR.reemKufi,
        'Reem Kufi Fun': PartR.reemKufiFun,
        'Reem Kufi Ink': PartR.reemKufiInk,
        'Reenie Beanie': PartR.reenieBeanie,
        'Reggae One': PartR.reggaeOne,
        'Rethink Sans': PartR.rethinkSans,
        'Revalia': PartR.revalia,
        'Rhodium Libre': PartR.rhodiumLibre,
        'Ribeye': PartR.ribeye,
        'Ribeye Marrow': PartR.ribeyeMarrow,
        'Righteous': PartR.righteous,
        'Risque': PartR.risque,
        'Road Rage': PartR.roadRage,
        'Roboto': PartR.roboto,
        'Roboto Condensed': PartR.robotoCondensed,
        'Roboto Flex': PartR.robotoFlex,
        'Roboto Mono': PartR.robotoMono,
        'Roboto Serif': PartR.robotoSerif,
        'Roboto Slab': PartR.robotoSlab,
        'Rochester': PartR.rochester,
        'Rock 3D': PartR.rock3d,
        'Rock Salt': PartR.rockSalt,
        'RocknRoll One': PartR.rocknRollOne,
        'Rokkitt': PartR.rokkitt,
        'Romanesco': PartR.romanesco,
        'Ropa Sans': PartR.ropaSans,
        'Rosario': PartR.rosario,
        'Rosarivo': PartR.rosarivo,
        'Rouge Script': PartR.rougeScript,
        'Rowdies': PartR.rowdies,
        'Rozha One': PartR.rozhaOne,
        'Rubik': PartR.rubik,
        'Rubik 80s Fade': PartR.rubik80sFade,
        'Rubik Beastly': PartR.rubikBeastly,
        'Rubik Broken Fax': PartR.rubikBrokenFax,
        'Rubik Bubbles': PartR.rubikBubbles,
        'Rubik Burned': PartR.rubikBurned,
        'Rubik Dirt': PartR.rubikDirt,
        'Rubik Distressed': PartR.rubikDistressed,
        'Rubik Doodle Shadow': PartR.rubikDoodleShadow,
        'Rubik Doodle Triangles': PartR.rubikDoodleTriangles,
        'Rubik Gemstones': PartR.rubikGemstones,
        'Rubik Glitch': PartR.rubikGlitch,
        'Rubik Glitch Pop': PartR.rubikGlitchPop,
        'Rubik Iso': PartR.rubikIso,
        'Rubik Lines': PartR.rubikLines,
        'Rubik Maps': PartR.rubikMaps,
        'Rubik Marker Hatch': PartR.rubikMarkerHatch,
        'Rubik Maze': PartR.rubikMaze,
        'Rubik Microbe': PartR.rubikMicrobe,
        'Rubik Mono One': PartR.rubikMonoOne,
        'Rubik Moonrocks': PartR.rubikMoonrocks,
        'Rubik Pixels': PartR.rubikPixels,
        'Rubik Puddles': PartR.rubikPuddles,
        'Rubik Scribble': PartR.rubikScribble,
        'Rubik Spray Paint': PartR.rubikSprayPaint,
        'Rubik Storm': PartR.rubikStorm,
        'Rubik Vinyl': PartR.rubikVinyl,
        'Rubik Wet Paint': PartR.rubikWetPaint,
        'Ruda': PartR.ruda,
        'Rufina': PartR.rufina,
        'Ruge Boogie': PartR.rugeBoogie,
        'Ruluko': PartR.ruluko,
        'Rum Raisin': PartR.rumRaisin,
        'Ruslan Display': PartR.ruslanDisplay,
        'Russo One': PartR.russoOne,
        'Ruthie': PartR.ruthie,
        'Ruwudu': PartR.ruwudu,
        'Rye': PartR.rye,
        'STIX Two Text': PartS.stixTwoText,
        'Sacramento': PartS.sacramento,
        'Sahitya': PartS.sahitya,
        'Sail': PartS.sail,
        'Saira': PartS.saira,
        'Saira Condensed': PartS.sairaCondensed,
        'Saira Extra Condensed': PartS.sairaExtraCondensed,
        'Saira Semi Condensed': PartS.sairaSemiCondensed,
        'Saira Stencil One': PartS.sairaStencilOne,
        'Salsa': PartS.salsa,
        'Sanchez': PartS.sanchez,
        'Sancreek': PartS.sancreek,
        'Sansita': PartS.sansita,
        'Sansita Swashed': PartS.sansitaSwashed,
        'Sarabun': PartS.sarabun,
        'Sarala': PartS.sarala,
        'Sarina': PartS.sarina,
        'Sarpanch': PartS.sarpanch,
        'Sassy Frass': PartS.sassyFrass,
        'Satisfy': PartS.satisfy,
        'Sawarabi Gothic': PartS.sawarabiGothic,
        'Sawarabi Mincho': PartS.sawarabiMincho,
        'Scada': PartS.scada,
        'Scheherazade New': PartS.scheherazadeNew,
        'Schibsted Grotesk': PartS.schibstedGrotesk,
        'Schoolbell': PartS.schoolbell,
        'Scope One': PartS.scopeOne,
        'Seaweed Script': PartS.seaweedScript,
        'Secular One': PartS.secularOne,
        'Sedan': PartS.sedan,
        'Sedan SC': PartS.sedanSc,
        'Sedgwick Ave': PartS.sedgwickAve,
        'Sedgwick Ave Display': PartS.sedgwickAveDisplay,
        'Sen': PartS.sen,
        'Send Flowers': PartS.sendFlowers,
        'Sevillana': PartS.sevillana,
        'Seymour One': PartS.seymourOne,
        'Shadows Into Light': PartS.shadowsIntoLight,
        'Shadows Into Light Two': PartS.shadowsIntoLightTwo,
        'Shalimar': PartS.shalimar,
        'Shantell Sans': PartS.shantellSans,
        'Shanti': PartS.shanti,
        'Share': PartS.share,
        'Share Tech': PartS.shareTech,
        'Share Tech Mono': PartS.shareTechMono,
        'Shippori Antique': PartS.shipporiAntique,
        'Shippori Antique B1': PartS.shipporiAntiqueB1,
        'Shippori Mincho': PartS.shipporiMincho,
        'Shippori Mincho B1': PartS.shipporiMinchoB1,
        'Shizuru': PartS.shizuru,
        'Shojumaru': PartS.shojumaru,
        'Short Stack': PartS.shortStack,
        'Shrikhand': PartS.shrikhand,
        'Siemreap': PartS.siemreap,
        'Sigmar': PartS.sigmar,
        'Sigmar One': PartS.sigmarOne,
        'Signika': PartS.signika,
        'Signika Negative': PartS.signikaNegative,
        'Silkscreen': PartS.silkscreen,
        'Simonetta': PartS.simonetta,
        'Single Day': PartS.singleDay,
        'Sintony': PartS.sintony,
        'Sirin Stencil': PartS.sirinStencil,
        'Six Caps': PartS.sixCaps,
        'Sixtyfour': PartS.sixtyfour,
        'Skranji': PartS.skranji,
        'Slabo 13px': PartS.slabo13px,
        'Slabo 27px': PartS.slabo27px,
        'Slackey': PartS.slackey,
        'Slackside One': PartS.slacksideOne,
        'Smokum': PartS.smokum,
        'Smooch': PartS.smooch,
        'Smooch Sans': PartS.smoochSans,
        'Smythe': PartS.smythe,
        'Sniglet': PartS.sniglet,
        'Snippet': PartS.snippet,
        'Snowburst One': PartS.snowburstOne,
        'Sofadi One': PartS.sofadiOne,
        'Sofia': PartS.sofia,
        'Sofia Sans': PartS.sofiaSans,
        'Sofia Sans Condensed': PartS.sofiaSansCondensed,
        'Sofia Sans Extra Condensed': PartS.sofiaSansExtraCondensed,
        'Sofia Sans Semi Condensed': PartS.sofiaSansSemiCondensed,
        'Solitreo': PartS.solitreo,
        'Solway': PartS.solway,
        'Sometype Mono': PartS.sometypeMono,
        'Song Myung': PartS.songMyung,
        'Sono': PartS.sono,
        'Sonsie One': PartS.sonsieOne,
        'Sora': PartS.sora,
        'Sorts Mill Goudy': PartS.sortsMillGoudy,
        'Source Code Pro': PartS.sourceCodePro,
        'Source Sans 3': PartS.sourceSans3,
        'Source Serif 4': PartS.sourceSerif4,
        'Space Grotesk': PartS.spaceGrotesk,
        'Space Mono': PartS.spaceMono,
        'Special Elite': PartS.specialElite,
        'Spectral': PartS.spectral,
        'Spectral SC': PartS.spectralSc,
        'Spicy Rice': PartS.spicyRice,
        'Spinnaker': PartS.spinnaker,
        'Spirax': PartS.spirax,
        'Splash': PartS.splash,
        'Spline Sans': PartS.splineSans,
        'Spline Sans Mono': PartS.splineSansMono,
        'Squada One': PartS.squadaOne,
        'Square Peg': PartS.squarePeg,
        'Sree Krushnadevaraya': PartS.sreeKrushnadevaraya,
        'Sriracha': PartS.sriracha,
        'Srisakdi': PartS.srisakdi,
        'Staatliches': PartS.staatliches,
        'Stalemate': PartS.stalemate,
        'Stalinist One': PartS.stalinistOne,
        'Stardos Stencil': PartS.stardosStencil,
        'Stick': PartS.stick,
        'Stick No Bills': PartS.stickNoBills,
        'Stint Ultra Condensed': PartS.stintUltraCondensed,
        'Stint Ultra Expanded': PartS.stintUltraExpanded,
        'Stoke': PartS.stoke,
        'Strait': PartS.strait,
        'Style Script': PartS.styleScript,
        'Stylish': PartS.stylish,
        'Sue Ellen Francisco': PartS.sueEllenFrancisco,
        'Suez One': PartS.suezOne,
        'Sulphur Point': PartS.sulphurPoint,
        'Sumana': PartS.sumana,
        'Sunflower': PartS.sunflower,
        'Sunshiney': PartS.sunshiney,
        'Supermercado One': PartS.supermercadoOne,
        'Sura': PartS.sura,
        'Suranna': PartS.suranna,
        'Suravaram': PartS.suravaram,
        'Suwannaphum': PartS.suwannaphum,
        'Swanky and Moo Moo': PartS.swankyAndMooMoo,
        'Syncopate': PartS.syncopate,
        'Syne': PartS.syne,
        'Syne Mono': PartS.syneMono,
        'Syne Tactile': PartS.syneTactile,
        'Tac One': PartT.tacOne,
        'Tai Heritage Pro': PartT.taiHeritagePro,
        'Tajawal': PartT.tajawal,
        'Tangerine': PartT.tangerine,
        'Tapestry': PartT.tapestry,
        'Taprom': PartT.taprom,
        'Tauri': PartT.tauri,
        'Taviraj': PartT.taviraj,
        'Teachers': PartT.teachers,
        'Teko': PartT.teko,
        'Tektur': PartT.tektur,
        'Telex': PartT.telex,
        'Tenali Ramakrishna': PartT.tenaliRamakrishna,
        'Tenor Sans': PartT.tenorSans,
        'Text Me One': PartT.textMeOne,
        'Texturina': PartT.texturina,
        'Thasadith': PartT.thasadith,
        'The Girl Next Door': PartT.theGirlNextDoor,
        'The Nautigal': PartT.theNautigal,
        'Tienne': PartT.tienne,
        'Tillana': PartT.tillana,
        'Tilt Neon': PartT.tiltNeon,
        'Tilt Prism': PartT.tiltPrism,
        'Tilt Warp': PartT.tiltWarp,
        'Timmana': PartT.timmana,
        'Tinos': PartT.tinos,
        'Tiny5': PartT.tiny5,
        'Tiro Bangla': PartT.tiroBangla,
        'Tiro Devanagari Hindi': PartT.tiroDevanagariHindi,
        'Tiro Devanagari Marathi': PartT.tiroDevanagariMarathi,
        'Tiro Devanagari Sanskrit': PartT.tiroDevanagariSanskrit,
        'Tiro Gurmukhi': PartT.tiroGurmukhi,
        'Tiro Kannada': PartT.tiroKannada,
        'Tiro Tamil': PartT.tiroTamil,
        'Tiro Telugu': PartT.tiroTelugu,
        'Titan One': PartT.titanOne,
        'Titillium Web': PartT.titilliumWeb,
        'Tomorrow': PartT.tomorrow,
        'Tourney': PartT.tourney,
        'Trade Winds': PartT.tradeWinds,
        'Train One': PartT.trainOne,
        'Trirong': PartT.trirong,
        'Trispace': PartT.trispace,
        'Trocchi': PartT.trocchi,
        'Trochut': PartT.trochut,
        'Truculenta': PartT.truculenta,
        'Trykker': PartT.trykker,
        'Tsukimi Rounded': PartT.tsukimiRounded,
        'Tulpen One': PartT.tulpenOne,
        'Turret Road': PartT.turretRoad,
        'Twinkle Star': PartT.twinkleStar,
        'Ubuntu': PartU.ubuntu,
        'Ubuntu Condensed': PartU.ubuntuCondensed,
        'Ubuntu Mono': PartU.ubuntuMono,
        'Ubuntu Sans': PartU.ubuntuSans,
        'Ubuntu Sans Mono': PartU.ubuntuSansMono,
        'Uchen': PartU.uchen,
        'Ultra': PartU.ultra,
        'Unbounded': PartU.unbounded,
        'Uncial Antiqua': PartU.uncialAntiqua,
        'Underdog': PartU.underdog,
        'Unica One': PartU.unicaOne,
        'UnifrakturCook': PartU.unifrakturCook,
        'UnifrakturMaguntia': PartU.unifrakturMaguntia,
        'Unkempt': PartU.unkempt,
        'Unlock': PartU.unlock,
        'Unna': PartU.unna,
        'Updock': PartU.updock,
        'Urbanist': PartU.urbanist,
        'VT323': PartV.vt323,
        'Vampiro One': PartV.vampiroOne,
        'Varela': PartV.varela,
        'Varela Round': PartV.varelaRound,
        'Varta': PartV.varta,
        'Vast Shadow': PartV.vastShadow,
        'Vazirmatn': PartV.vazirmatn,
        'Vesper Libre': PartV.vesperLibre,
        'Viaoda Libre': PartV.viaodaLibre,
        'Vibes': PartV.vibes,
        'Vibur': PartV.vibur,
        'Victor Mono': PartV.victorMono,
        'Vidaloka': PartV.vidaloka,
        'Viga': PartV.viga,
        'Vina Sans': PartV.vinaSans,
        'Voces': PartV.voces,
        'Volkhov': PartV.volkhov,
        'Vollkorn': PartV.vollkorn,
        'Vollkorn SC': PartV.vollkornSc,
        'Voltaire': PartV.voltaire,
        'Vujahday Script': PartV.vujahdayScript,
        'Waiting for the Sunrise': PartW.waitingForTheSunrise,
        'Wallpoet': PartW.wallpoet,
        'Walter Turncoat': PartW.walterTurncoat,
        'Warnes': PartW.warnes,
        'Water Brush': PartW.waterBrush,
        'Waterfall': PartW.waterfall,
        'Wavefont': PartW.wavefont,
        'Wellfleet': PartW.wellfleet,
        'Wendy One': PartW.wendyOne,
        'Whisper': PartW.whisper,
        'WindSong': PartW.windSong,
        'Wire One': PartW.wireOne,
        'Wittgenstein': PartW.wittgenstein,
        'Wix Madefor Display': PartW.wixMadeforDisplay,
        'Wix Madefor Text': PartW.wixMadeforText,
        'Work Sans': PartW.workSans,
        'Workbench': PartW.workbench,
        'Xanh Mono': PartX.xanhMono,
        'Yaldevi': PartY.yaldevi,
        'Yanone Kaffeesatz': PartY.yanoneKaffeesatz,
        'Yantramanav': PartY.yantramanav,
        'Yarndings 12': PartY.yarndings12,
        'Yarndings 12 Charted': PartY.yarndings12Charted,
        'Yarndings 20': PartY.yarndings20,
        'Yarndings 20 Charted': PartY.yarndings20Charted,
        'Yatra One': PartY.yatraOne,
        'Yellowtail': PartY.yellowtail,
        'Yeon Sung': PartY.yeonSung,
        'Yeseva One': PartY.yesevaOne,
        'Yesteryear': PartY.yesteryear,
        'Yomogi': PartY.yomogi,
        'Young Serif': PartY.youngSerif,
        'Yrsa': PartY.yrsa,
        'Ysabeau': PartY.ysabeau,
        'Ysabeau Infant': PartY.ysabeauInfant,
        'Ysabeau Office': PartY.ysabeauOffice,
        'Ysabeau SC': PartY.ysabeauSc,
        'Yuji Boku': PartY.yujiBoku,
        'Yuji Hentaigana Akari': PartY.yujiHentaiganaAkari,
        'Yuji Hentaigana Akebono': PartY.yujiHentaiganaAkebono,
        'Yuji Mai': PartY.yujiMai,
        'Yuji Syuku': PartY.yujiSyuku,
        'Yusei Magic': PartY.yuseiMagic,
        'ZCOOL KuaiLe': PartZ.zcoolKuaiLe,
        'ZCOOL QingKe HuangYou': PartZ.zcoolQingKeHuangYou,
        'ZCOOL XiaoWei': PartZ.zcoolXiaoWei,
        'Zain': PartZ.zain,
        'Zen Antique': PartZ.zenAntique,
        'Zen Antique Soft': PartZ.zenAntiqueSoft,
        'Zen Dots': PartZ.zenDots,
        'Zen Kaku Gothic Antique': PartZ.zenKakuGothicAntique,
        'Zen Kaku Gothic New': PartZ.zenKakuGothicNew,
        'Zen Kurenaido': PartZ.zenKurenaido,
        'Zen Loop': PartZ.zenLoop,
        'Zen Maru Gothic': PartZ.zenMaruGothic,
        'Zen Old Mincho': PartZ.zenOldMincho,
        'Zen Tokyo Zoo': PartZ.zenTokyoZoo,
        'Zeyada': PartZ.zeyada,
        'Zhi Mang Xing': PartZ.zhiMangXing,
        'Zilla Slab': PartZ.zillaSlab,
        'Zilla Slab Highlight': PartZ.zillaSlabHighlight,
      };

  /// Get a map of all available fonts and their associated text themes.
  ///
  /// Returns a map where the key is the name of the font family and the value
  /// is the corresponding [GoogleFonts] `TextTheme` method.

  /// Retrieve a font by family name.
  ///
  /// Applies the given font family from Google Fonts to the given [textStyle]
  /// and returns the resulting [TextStyle].
  ///
  /// Note: [fontFamily] is case-sensitive.
  ///
  /// Parameter [fontFamily] must not be `null`. Throws if no font by name
  /// [fontFamily] exists.
  static CustomTextStyle getFont(
    String fontFamily, {
    CustomTextStyle? textStyle,
    Color? color,
    Color? backgroundColor,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    Locale? locale,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
  }) {
    final fonts = GoogleFonts.asMap();
    if (!fonts.containsKey(fontFamily)) {
      throw Exception("No font family by name '$fontFamily' was found.");
    }
    return fonts[fontFamily]!(
      textStyle: textStyle,
      color: color,
      backgroundColor: backgroundColor,
      fontSize: fontSize,
      fontWeight: fontWeight,
      fontStyle: fontStyle,
      letterSpacing: letterSpacing,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      height: height,
      locale: locale,
      foreground: foreground,
      background: background,
      shadows: shadows,
      fontFeatures: fontFeatures,
      decoration: decoration,
      decorationColor: decorationColor,
      decorationStyle: decorationStyle,
      decorationThickness: decorationThickness,
    );
  }
}
